controller_manager:
  ros__parameters:
    update_rate: 50

joint_state_broadcaster:
  ros__parameters:
    type: "joint_state_broadcaster/JointStateBroadcaster"
    publish_rate: 50

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_front_wheel_joint", "left_rear_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint", "right_rear_wheel_joint"]
    wheel_separation: 0.08
    wheel_radius: 0.033
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    odom_frame: "odom"
    base_frame: "base_link"
    enable_odom_tf: true
    publish_rate: 50
